project = 'Selenitas'
description = 'A multiagent system simulator written in Lua'
full_description = [[
        TODO: A full description here.

        .
]]
file = {
        '.',
        exclude = {
                'conf.lua',
                'Thirdparty/',
                'Examples_without_graphical_engine/',
                'Resources/examples'
                }
       }

not_luadoc=true
no_summary = true
no_return_or_parms = true
format = 'discount'
