name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Create .love file
      run: |
        cd $GITHUB_WORKSPACE
        zip -9 -r -q Selenitas.love .
        mkdir artifacts
        cp Selenitas.love artifacts
    
    - name: Get love.exe
      run: |
        cd $GITHUB_WORKSPACE
        wget https://github.com/love2d/love/releases/download/11.3/love-11.3-win64.zip
        unzip -D love-11.3-win64.zip
        
    - name: Build for Windows
      run: |
        cd $GITHUB_WORKSPACE
        cd love-11.3-win64
        cat love.exe artifacts/Selenitas.love > Selenitas.exe
        cd ..
        mkdir selenitas-windows
        cp love-11.3-win64/*.dll selenitas-windows
        cp love-11.3-win64/Selenitas.exe selenitas-windows
        cp love-11.3-win64/license.txt selenitas-windows
        zip -9 -r selenitas-windows.zip selenitas-windows
        cp selenitas-windows.zip artifacts
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: selenitas-artifacts
        path:
          artifacts      
