name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: sudo apt-get install --assume-yes wine-stable wine64 python3-pip
      
    - name: Checkout makelove tool
      uses: actions/checkout@v2
      with:
        repository: pfirsich/makelove
        path: makelove
      
    - name: Install makelove tool
      run: pip3 install ./makelove
      
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        python3 -m makelove
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: selenitas-artifacts
        path:
          build      
