name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install python3 python3-pip
        sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
        sudo apt install --install-recommends winehq-stable
        pip3 install makelove
  
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        makelove
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: selenitas-artifacts
        path:
          build      
