name: CI 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    # Linux version built on Ubuntu 20.04
    runs-on: ubuntu-20.04

    # Build steps
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install system dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --assume-yes python3-pip

    # Install makelove
    - name: Install makelove tool
      run: pip3 install makelove
      
    # Build for Linux (AppImage)
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        python3 -m makelove appimage 
    
    # Upload built artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: selenitas-linux-artifacts
        path:
          build
          
  build-windows:
    # Windows version built on Ubuntu 20.04
    runs-on: ubuntu-20.04

    # Build steps
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install dependencies for Windows
    # Makelove is used for Windows build checking and .love generation,
    # actual executable is a batch file created in this job using Love2D 11.3
    # This is because Love2D builds in fused mode cause problems when accesing the Windows filesystem
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --assume-yes wine-stable wine64 python3-pip wget

    # Install makelove
    - name: Install makelove tool
      run: pip3 install makelove
      
    # Build for Windows x64 
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        python3 -m makelove win64
        cd build
        mv win64 files
        mkdir files/love2d
        mv love/Selenitas.love files
        rm -rf love
        cd files
        rm Selenitas-win64.zip
        cd love2d
        wget https://github.com/love2d/love/releases/download/11.3/love-11.3-win64.zip
        unzip love-11.3-win64.zip
        rm love-11.3-win64.zip
        mv love-11.3-win64/* .
        cd ../..
        touch Selenitas.bat
        echo "start files\love2d\love.exe files\Selenitas.love" > Selenitas.bat
        
    # Upload built artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: selenitas-windows-artifacts
        path:
          build 

  build-macos:
    # Linux version built on MacOS 10.15
    runs-on: macos-10.15

    # Build steps
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install dependencies
    # XCode 11 is used
    - name: Install dependencies
      run: |
        sudo xcode-select -switch /Applications/Xcode_11.3.app
        brew install libtiff libjpeg webp little-cms2

    # Install makelove including needed headers
    - name: Install makelove tool
      run: |
        CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pip3.8 install makelove
      
    # Build for MacOS
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        python3 -m makelove macos 
    
    # Upload built artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: selenitas-macos-artifacts
        path:
          build
